baseURL = "single-page-blog.netlify.app"
languageCode = "en-us"
theme = "blog"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Blog"
  URL = "#portfolio"
  weight = 3


  [[menu.header]]
  name = "categories"
  URL = "#categories"
  weight = 4

  [[menu.header]]
  name = "tags"
  URL = "#tags"
  weight = 5

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 6


  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 4


[params]

  sections = ["showcase", "about","client-and-work","contact"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Megam"
    text2 = "Solutions"

  [params.footer]
      copyright = "© MegamSolution. All rights reserved."
     